// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBccZtRb-KAyKU-YmndSrlUSphgo1HAqxU',
    appId: '1:499354494780:web:ebf5a0704f950e6a6be039',
    messagingSenderId: '499354494780',
    projectId: 'flutter-tobeto',
    authDomain: 'flutter-tobeto.firebaseapp.com',
    storageBucket: 'flutter-tobeto.appspot.com',
    measurementId: 'G-P0YJYYZNC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQh7hkvMbIyVTQVZ1tmNXfc8yeMsxu9yM',
    appId: '1:499354494780:android:9ec54b00abb9a7d06be039',
    messagingSenderId: '499354494780',
    projectId: 'flutter-tobeto',
    storageBucket: 'flutter-tobeto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyHQ2aS3ZN4DhTKjg1apcljlAUbvM5Rqk',
    appId: '1:499354494780:ios:332ab463ff8da0d46be039',
    messagingSenderId: '499354494780',
    projectId: 'flutter-tobeto',
    storageBucket: 'flutter-tobeto.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyHQ2aS3ZN4DhTKjg1apcljlAUbvM5Rqk',
    appId: '1:499354494780:ios:332ab463ff8da0d46be039',
    messagingSenderId: '499354494780',
    projectId: 'flutter-tobeto',
    storageBucket: 'flutter-tobeto.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBccZtRb-KAyKU-YmndSrlUSphgo1HAqxU',
    appId: '1:499354494780:web:c75b5b530dfb7d876be039',
    messagingSenderId: '499354494780',
    projectId: 'flutter-tobeto',
    authDomain: 'flutter-tobeto.firebaseapp.com',
    storageBucket: 'flutter-tobeto.appspot.com',
    measurementId: 'G-R1MGHWC3KM',
  );
}
