// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKODmPi5IWHvzhSLn2UX56SmnlnaGEzwI',
    appId: '1:516162765810:web:5d4ccb70a06bba57c8e16b',
    messagingSenderId: '516162765810',
    projectId: 'tobeto-2a',
    authDomain: 'tobeto-2a.firebaseapp.com',
    storageBucket: 'tobeto-2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyNwbfyvF4UsXip8ImAe_mmhcFjnDzU9c',
    appId: '1:516162765810:android:a275f06ef24e7fe3c8e16b',
    messagingSenderId: '516162765810',
    projectId: 'tobeto-2a',
    storageBucket: 'tobeto-2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Z-cx-P4-MybEQVDgYTmbQ3llKWLtB8U',
    appId: '1:516162765810:ios:04374284825a480fc8e16b',
    messagingSenderId: '516162765810',
    projectId: 'tobeto-2a',
    storageBucket: 'tobeto-2a.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Z-cx-P4-MybEQVDgYTmbQ3llKWLtB8U',
    appId: '1:516162765810:ios:04374284825a480fc8e16b',
    messagingSenderId: '516162765810',
    projectId: 'tobeto-2a',
    storageBucket: 'tobeto-2a.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKODmPi5IWHvzhSLn2UX56SmnlnaGEzwI',
    appId: '1:516162765810:web:7a7c26b0d12f255ec8e16b',
    messagingSenderId: '516162765810',
    projectId: 'tobeto-2a',
    authDomain: 'tobeto-2a.firebaseapp.com',
    storageBucket: 'tobeto-2a.appspot.com',
  );
}
